name: build and deploy to gh-pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # workflow_dispatch:
  #   inputs:
  #     name:
  #       description: 'Artifact name'
  #       required: false
  #       default: 'github-pages'
  #     path:
  #       description: "Path of the directory containing the static assets."
  #       required: false
  #       default: "dist/"
  #     retention-days:
  #       description: "Duration after which artifact will expire in days."
  #       required: false
  #       default: "1"
    

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    using: composite
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: make install

    - name: Build frontend
      run: make build

    # - name: Archive artifact
    #   shell: sh
    #   if: runner.os == 'Linux'
    #   run: |
    #     chmod -c -R +rX "$INPUT_PATH" | while read line; do
    #       echo "::warning title=Invalid file permissions automatically fixed::$line"
    #     done
    #     tar \
    #       --dereference --hard-dereference \
    #       --directory "$INPUT_PATH" \
    #       -cvf artifact.tar \
    #       --exclude=.git \
    #       --exclude=.github \
    #       .
    #   env:
    #     INPUT_PATH: ${{ inputs.path }}

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v1.0.8

    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v2.0.1

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: ${{ inputs.name }}
    #     path: dist/artifact.tar
    #     retention-days: ${{ inputs.retention-days }}
    #     if-no-files-found: error
